# The main workflow is intended to run unit tests on each commit to or pull request made to develop
name: Unit Tests
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out Develop and Release so we can build and perform unit tests on the external solution, Unity
      # Always check out develop so our GitVersion task will complete when building the external solution
      # and ensure fetch-depth is zero to avoid errors with GitVersion
      - uses: actions/checkout@v2
        with:
          ref: 'develop'
          fetch-depth: 0

      - uses: actions/cache@v1.1.0
        with:
          path: Unity/Library
          key: Library-EntitasRedux-Windows
          restore-keys: |
            Library-EntitasRedux-
            Library-
            
      # Execute Unity Unit Tests and Upload results
    - name: Run Unity Unit Tests
      uses: game-ci/unity-test-runner@v2.0-alpha-3
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      with:
        projectPath: './Unity'
        unityVersion: 2019.4.20f1

    - name: Upload Unit Test Results
      uses: actions/upload-artifact@v1
      with:
        name: Test results
        path: artifacts
      
      # Return Unity License
      - name: Return Unity license
        uses: game-ci/unity-return-license@v1
        if: always()
